# Generated by Django 5.1.7 on 2025-04-02 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="bid",
            name="message",
            field=models.TextField(blank=True, default="No message provided"),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="rejection_reason",
            field=models.TextField(blank=True, null=True),
        ),
    ]
