# Generated by Django 5.1.7 on 2025-04-20 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_bid_message_vehicle_rejection_reason"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicle",
            name="is_visible",
            field=models.BooleanField(default=True),
        ),
    ]
