# Generated by Django 5.1.7 on 2025-08-16 18:55

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_vehicleview_websitevisit"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="quoterequest",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Quote Request",
                "verbose_name_plural": "Quote Requests",
            },
        ),
        migrations.AddField(
            model_name="quoterequest",
            name="admin_notes",
            field=models.TextField(
                blank=True, help_text="Internal notes for admin use"
            ),
        ),
        migrations.AddField(
            model_name="quoterequest",
            name="email_sent_at",
            field=models.DateTimeField(
                blank=True, help_text="When the quote email was sent", null=True
            ),
        ),
        migrations.AddField(
            model_name="quoterequest",
            name="priority",
            field=models.CharField(
                choices=[
                    ("low", "Low"),
                    ("medium", "Medium"),
                    ("high", "High"),
                    ("urgent", "Urgent"),
                ],
                default="medium",
                help_text="Priority level of this quote",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="quoterequest",
            name="processed_at",
            field=models.DateTimeField(
                blank=True, help_text="When this quote was processed", null=True
            ),
        ),
        migrations.AddField(
            model_name="quoterequest",
            name="processed_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Admin user who processed this quote",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="processed_quotes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="quoterequest",
            name="quote_email_sent",
            field=models.BooleanField(
                default=False, help_text="Whether quote email was sent successfully"
            ),
        ),
        migrations.AddField(
            model_name="quoterequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("reviewed", "Reviewed"),
                    ("quoted", "Quoted"),
                    ("converted", "Converted"),
                    ("expired", "Expired"),
                ],
                default="pending",
                help_text="Current status of the quote request",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="quoterequest",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="quoterequest",
            name="address",
            field=models.TextField(
                blank=True, help_text="Customer's address (optional)"
            ),
        ),
        migrations.AlterField(
            model_name="quoterequest",
            name="city",
            field=models.CharField(help_text="Customer's city", max_length=100),
        ),
        migrations.AlterField(
            model_name="quoterequest",
            name="country",
            field=models.CharField(help_text="Customer's country", max_length=100),
        ),
        migrations.AlterField(
            model_name="quoterequest",
            name="email",
            field=models.EmailField(
                help_text="Customer's email address",
                max_length=254,
                validators=[django.core.validators.EmailValidator()],
            ),
        ),
        migrations.AlterField(
            model_name="quoterequest",
            name="full_name",
            field=models.CharField(help_text="Customer's full name", max_length=255),
        ),
        migrations.AlterField(
            model_name="quoterequest",
            name="is_processed",
            field=models.BooleanField(
                default=False,
                help_text="Whether this quote has been processed by admin",
            ),
        ),
        migrations.AlterField(
            model_name="quoterequest",
            name="note",
            field=models.TextField(
                blank=True, help_text="Additional notes from customer"
            ),
        ),
        migrations.AlterField(
            model_name="quoterequest",
            name="telephone",
            field=models.CharField(
                help_text="Customer's phone number with country code",
                max_length=20,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Enter a valid phone number",
                        regex="^[\\+]?[\\d\\s\\-\\(\\)]{8,}$",
                    )
                ],
            ),
        ),
        migrations.AddIndex(
            model_name="quoterequest",
            index=models.Index(
                fields=["created_at"], name="core_quoter_created_bdf47e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="quoterequest",
            index=models.Index(fields=["email"], name="core_quoter_email_e0a36d_idx"),
        ),
        migrations.AddIndex(
            model_name="quoterequest",
            index=models.Index(fields=["status"], name="core_quoter_status_34f9e5_idx"),
        ),
        migrations.AddIndex(
            model_name="quoterequest",
            index=models.Index(
                fields=["is_processed"], name="core_quoter_is_proc_d8dd4a_idx"
            ),
        ),
    ]
