# Generated by Django 5.1.7 on 2025-04-21 08:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_vehicle_is_visible"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vehicle",
            name="images",
        ),
        migrations.AddField(
            model_name="vehicleimage",
            name="vehicle",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="core.vehicle",
            ),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="mileage",
            field=models.PositiveIntegerField(
                help_text="Current vehicle mileage in kilometers"
            ),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="proposed_price",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Price you expect for instant sale",
                max_digits=10,
                verbose_name="Asking Price",
            ),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="vin",
            field=models.CharField(
                help_text="Vehicle Identification Number", max_length=17, unique=True
            ),
        ),
    ]
