# Generated by Django 5.1.7 on 2025-09-02 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_quoterequest_options_quoterequest_admin_notes_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicle",
            name="body_type",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
