# Generated by Django 5.1.7 on 2025-04-23 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_remove_vehicle_images_vehicleimage_vehicle_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehicle",
            name="proposed_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Price you expect for instant sale",
                max_digits=10,
                null=True,
                verbose_name="Asking Price",
            ),
        ),
    ]
