# Generated by Django 5.1.7 on 2025-09-06 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_vehicle_body_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicle",
            name="transmission",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
