# Generated by Django 5.1.7 on 2025-09-06 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_vehicle_transmission"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehicle",
            name="mileage",
            field=models.CharField(
                blank=True,
                help_text="Current vehicle mileage in kilometers",
                max_length=20,
            ),
        ),
    ]
