# Generated by Django 5.1.7 on 2025-05-09 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_alter_bid_vehicle_notification_vehiclesearch"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicle",
            name="fuel_type",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
