# Generated by Django 5.1.7 on 2025-09-07 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_alter_vehicle_mileage"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vehiclesearch",
            name="max_mileage",
        ),
    ]
