# Generated by Django 5.1.7 on 2025-06-18 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_vehicle_location_quoterequest"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="quoterequest",
            name="user",
        ),
    ]
