# Generated by Django 4.2.27 on 2026-01-20 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_jobposition_profile_email_verification_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposition',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
