# Generated by Django 5.1.7 on 2025-06-19 21:18

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_remove_quoterequest_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="vehicle",
            options={"ordering": ["-created_at"]},
        ),
        migrations.RemoveField(
            model_name="vehicle",
            name="status",
        ),
        migrations.AddField(
            model_name="vehicle",
            name="digitally_verified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="digitally_verified_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="digital_verifications",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="is_digitally_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="is_physically_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="is_rejected",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="physically_verified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="physically_verified_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="physical_verifications",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="verification_state",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("digital", "Digitally Verified"),
                    ("physical", "Physically Verified"),
                    ("rejected", "Rejected"),
                ],
                db_index=True,
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="location",
            field=models.CharField(
                blank=True, db_index=True, default=None, max_length=50, null=True
            ),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="vin",
            field=models.CharField(
                db_index=True,
                help_text="Vehicle Identification Number",
                max_length=17,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="year",
            field=models.PositiveIntegerField(
                validators=[
                    django.core.validators.MinValueValidator(1900),
                    django.core.validators.MaxValueValidator(2026),
                ]
            ),
        ),
        migrations.AddIndex(
            model_name="vehicle",
            index=models.Index(
                fields=["is_digitally_verified", "is_physically_verified"],
                name="core_vehicl_is_digi_c762f8_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="vehicle",
            index=models.Index(
                fields=["listing_type", "is_visible"],
                name="core_vehicl_listing_2578c7_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="vehicle",
            index=models.Index(
                fields=["make", "model"], name="core_vehicl_make_660e6b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vehicle",
            index=models.Index(fields=["price"], name="core_vehicl_price_eaa28f_idx"),
        ),
        migrations.AddIndex(
            model_name="vehicle",
            index=models.Index(
                fields=["created_at"], name="core_vehicl_created_b6d742_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="vehicle",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("verification_state", "rejected"), _negated=True),
                    ("rejection_reason__isnull", False),
                    _connector="OR",
                ),
                name="rejection_requires_reason",
            ),
        ),
        migrations.AddConstraint(
            model_name="vehicle",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("listing_type", "marketplace"), ("price__isnull", False)),
                    models.Q(
                        ("listing_type", "instant_sale"),
                        ("proposed_price__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="valid_pricing_for_listing_type",
            ),
        ),
    ]
