# Generated by Django 5.1.7 on 2025-06-19 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_alter_vehicle_options_remove_vehicle_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicle",
            name="rejected_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
