# Generated by Django 5.1.7 on 2025-07-02 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_vehicle_rejected_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="TestUpload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("test_file", models.FileField(upload_to="test_uploads/")),
            ],
            options={
                "verbose_name": "Test Upload",
            },
        ),
    ]
