# Generated by Django 4.2.27 on 2026-01-20 09:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0011_sellerreview_sellerbadge'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(default=dict, help_text='Vehicle form data')),
                ('images', models.JSONField(default=list, help_text='List of uploaded image URLs')),
                ('step', models.PositiveIntegerField(default=1, help_text='Current form step (1-5)')),
                ('is_complete', models.BooleanField(default=False)),
                ('draft_title', models.CharField(blank=True, help_text='Auto-generated from make/model if available', max_length=100)),
                ('expires_at', models.DateTimeField(help_text='Draft will be auto-deleted after this date')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_drafts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vehicle Draft',
                'verbose_name_plural': 'Vehicle Drafts',
                'ordering': ['-updated_at'],
            },
        ),
    ]
